version: "3"
services:
  node-express-docker:
    build: ./api
    container_name: node-express-docker
    environment:
      - NODE_ENV=development
    volumes:
      - ./api:/app
      - /app/node_modules
    restart: always
    expose:
      - "4000"
    ports:
      - "4000:4000"
    command: npm run dev


  frontend:
    build: ./frontend 
    container_name: frontend
    ports:
      - '3000:3000'
    volumes:
        - ./frontend:/app
        - node_modules:/app/node_modules
    stdin_open: true
    tty: true  


  postgres:
    image: postgres
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
  node_modules:

